version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@5.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - setup_remote_docker
      - run:
          name: Check AWS CLI
          command: aws --version
      - run:
          name: Build
          command: cd frontend && make build && cd ..

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - ACOER
          filters:
            branches:
              only: main