export const batchStatusUpdates = [
  {
    previousStatus: "Unprocessed",
    currentStatus: "Manufactured",
    inputs: [
      {
        id: "manufacturer",
        label: "Manufacturer",
        type: "text",
        required: true,
        placeholder: "Enter Manufacturer",
      },
      {
        id: "location",
        label: "Location",
        type: "text",
        required: true,
        placeholder: "Enter Location",
      },
      {
        id: "productionDate",
        label: "Production Date",
        type: "auto",
        required: true,
      },
      {
        id: "productionTime",
        label: "Production Time",
        type: "auto",
        required: true,
      },
      {
        id: "expirationDate",
        label: "Expiration Date",
        type: "date",
        required: true,
        placeholder: "Enter Expiration Date",
      },
    ],
  },
  {
    previousStatus: "Manufactured",
    currentStatus: "QC-Pending",
    inputs: [
      {
        id: "qcStation",
        label: "QC Station",
        type: "text",
        required: true,
        placeholder: "Enter QC Station",
      },
      {
        id: "location",
        label: "Location",
        type: "text",
        required: true,
        placeholder: "Enter Location",
      },
      {
        id: "date",
        label: "Date",
        type: "auto",
        required: true,
      },
      {
        id: "time",
        label: "Time",
        type: "auto",
        required: true,
      },
    ],
  },
  {
    previousStatus: "QC-Pending",
    currentStatus: "QC-Passed",
    inputs: [
      {
        id: "qcStation",
        label: "QC Station",
        type: "text",
        required: true,
        placeholder: "Enter QC Station",
      },
      {
        id: "qcInspectorId",
        label: "QC Inspector ID",
        type: "text",
        required: true,
        placeholder: "Enter QC Inspector ID",
      },
      {
        id: "location",
        label: "Location",
        type: "text",
        required: true,
        placeholder: "Enter Location",
      },
      {
        id: "date",
        label: "Date",
        type: "auto",
        required: true,
      },
      {
        id: "time",
        label: "Time",
        type: "auto",
        required: true,
      },
    ],
  },
  {
    previousStatus: "QC-Passed",
    currentStatus: "Shipped",
    inputs: [
      {
        id: "carrier",
        label: "Carrier",
        type: "text",
        required: true,
        placeholder: "Enter Carrier",
      },
      {
        id: "trackingId",
        label: "Tracking ID",
        type: "text",
        required: true,
        placeholder: "Enter Tracking ID",
      },
      {
        id: "date",
        label: "Date",
        type: "auto",
        required: true,
      },
      {
        id: "time",
        label: "Time",
        type: "auto",
        required: true,
      },
      {
        id: "transportMode",
        label: "Transport Mode",
        type: "text",
        required: true,
        placeholder: "Enter Transport Mode",
      },
      {
        id: "originAddress",
        label: "Origin Address",
        type: "text",
        required: true,
        placeholder: "Enter Origin Address",
      },
      {
        id: "destinationAddress",
        label: "Destination Address",
        type: "text",
        required: true,
        placeholder: "Enter Destination Address",
      },
    ],
  },
  {
    previousStatus: "Shipped",
    currentStatus: "Received",
    inputs: [
      {
        id: "receiverLocation",
        label: "Received Location",
        type: "text",
        required: true,
        placeholder: "Enter Received Location",
      },
      {
        id: "receiver",
        label: "Receiver",
        type: "text",
        required: true,
        placeholder: "Enter Receiver",
      },
      {
        id: "date",
        label: "Date",
        type: "auto",
        required: true,
      },
      {
        id: "time",
        label: "Time",
        type: "auto",
        required: true,
      },
    ],
  },
];
